/**
 * Styles for HomeCreateSection.
 *
 * Keeping this separate from create-section.tsx keeps the component file focused
 * on behavior and makes the layout easier to scan during code review.
 */
import { StyleSheet } from 'react-native';

import { COLORS, RADIUS, SHADOWS, SPACING } from '@/constants/design';

export { COLORS };

export const styles = StyleSheet.create({
  section: {
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    gap: SPACING.md,
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: COLORS.line,
    ...SHADOWS.soft,
  },
  createSection: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: COLORS.createPaper,
    borderColor: COLORS.createCrayon,
    borderTopColor: COLORS.create,
    borderTopWidth: 4,
  },
  createCollapsedSection: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: COLORS.createPaper,
    borderColor: COLORS.createCrayon,
    minHeight: 132,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    ...SHADOWS.card,
  },
  sectionHeader: {
    position: 'relative',
    gap: 4,
  },
  sectionLabel: {
    color: COLORS.createDeep,
    fontSize: 28,
    fontWeight: '800',
  },
  createCollapsedLabel: {
    color: COLORS.createDeep,
  },
  sectionKicker: {
    color: COLORS.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  createCollapsedText: {
    position: 'relative',
    color: COLORS.createDeep,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  addCardActionRow: {
    alignItems: 'flex-end',
    paddingTop: 2,
    marginBottom: -2,
  },
  dropdownToggleRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  createBody: {
    position: 'relative',
    gap: SPACING.md,
    paddingTop: SPACING.md,
  },
  destinationRow: {
    position: 'relative',
    overflow: 'hidden',
    minHeight: 42,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: COLORS.createSoft,
    borderColor: COLORS.createCrayon,
    borderWidth: 1,
    gap: 3,
  },
  destinationLabel: {
    color: COLORS.createDeep,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  destinationValue: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  compactToggle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    borderRadius: RADIUS.md,
    paddingHorizontal: 10,
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: COLORS.line,
    gap: 7,
  },
  compactToggleNarrow: {
    flex: 1,
  },
  compactToggleWide: {
    flex: 1,
  },
  deckPickerToggleText: {
    color: COLORS.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
    textAlign: 'center',
    includeFontPadding: false,
  },
  deckPickerToggleChevron: {
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
    includeFontPadding: false,
  },
  input: {
    color: COLORS.ink,
    backgroundColor: COLORS.panel,
    borderColor: COLORS.line,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    lineHeight: 22,
    textAlignVertical: 'top',
  },
  frontInput: {
    minHeight: 92,
  },
  backInput: {
    minHeight: 112,
  },
  deckNameInput: {
    flex: 1,
    minHeight: 48,
  },
  deckButton: {
    position: 'relative',
    overflow: 'hidden',
    minHeight: 48,
    borderRadius: RADIUS.md,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.createSoft,
    borderWidth: 1,
    borderColor: COLORS.createCrayon,
  },
  deckButtonText: {
    color: COLORS.createDeep,
    fontSize: 14,
    fontWeight: '800',
  },
  deckPicker: {
    gap: SPACING.sm,
    paddingVertical: 6,
  },
  deckPickerPanel: {
    gap: SPACING.sm,
    backgroundColor: COLORS.panel,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.line,
    padding: 12,
    overflow: 'hidden',
  },
  newDeckPanel: {
    gap: SPACING.sm,
    backgroundColor: COLORS.panel,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.line,
    padding: 12,
    overflow: 'hidden',
  },
  deckChip: {
    position: 'relative',
    overflow: 'hidden',
    minWidth: 132,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.panelAlt,
    borderWidth: 1,
    borderColor: COLORS.line,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  deckChipActive: {
    backgroundColor: COLORS.createSoft,
    borderColor: COLORS.createCrayon,
  },
  deckChipText: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  deckChipTextActive: {
    color: COLORS.createDeep,
  },
  deckChipCount: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  primaryButton: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: COLORS.panelAlt,
    borderColor: COLORS.line,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    minHeight: 54,
    paddingHorizontal: 26,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonFloating: {
    width: '92%',
    maxWidth: 680,
  },
  primaryButtonPromptActive: {
    minHeight: 58,
    paddingHorizontal: 20,
    paddingVertical: 13,
    backgroundColor: COLORS.reviewSoft,
    borderColor: COLORS.reviewCrayon,
  },
  primaryButtonDisabled: {
    backgroundColor: COLORS.disabled,
    borderColor: COLORS.line,
  },
  primaryButtonText: {
    width: '100%',
    color: COLORS.ink,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '800',
    textAlign: 'center',
    includeFontPadding: true,
  },
  primaryButtonTextPromptActive: {
    color: COLORS.reviewDeep,
    fontWeight: '900',
  },
  primaryButtonTextDisabled: {
    color: COLORS.muted,
  },
  manageToggleButton: {
    position: 'relative',
    overflow: 'hidden',
    alignSelf: 'flex-end',
    minHeight: 34,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 14,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.panelAlt,
    borderColor: COLORS.line,
    borderWidth: 1,
  },
  manageToggleButtonText: {
    color: COLORS.ink,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  statusMessage: {
    position: 'relative',
    overflow: 'hidden',
    alignSelf: 'flex-start',
    backgroundColor: COLORS.createSoft,
    borderColor: COLORS.createCrayon,
    borderWidth: 1,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  statusMessageText: {
    color: COLORS.createDeep,
    fontSize: 13,
    fontWeight: '800',
  },

  managePanel: {
    backgroundColor: COLORS.panel,
    borderColor: COLORS.line,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: 12,
    gap: SPACING.sm,
  },
  manageHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: SPACING.sm,
  },
  manageTitleGroup: {
    flex: 1,
    gap: 3,
  },
  manageTitle: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  manageSubtitle: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  deleteDeckButton: {
    backgroundColor: COLORS.dangerSoft,
    borderColor: COLORS.dangerCrayon,
    borderWidth: 1,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  deleteDeckButtonText: {
    color: COLORS.danger,
    fontSize: 12,
    fontWeight: '900',
  },
  cardListWindow: {
    maxHeight: 304,
  },
  cardList: {
    gap: SPACING.sm,
    paddingRight: 4,
  },
  managedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.sm,
    backgroundColor: COLORS.panelAlt,
    borderColor: COLORS.line,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  managedCardTextGroup: {
    flex: 1,
    gap: 3,
  },
  managedCardFront: {
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 19,
  },
  managedCardBack: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  deleteCardButton: {
    backgroundColor: COLORS.dangerSoft,
    borderColor: COLORS.dangerCrayon,
    borderWidth: 1,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  deleteCardButtonText: {
    color: COLORS.danger,
    fontSize: 12,
    fontWeight: '900',
  },
  emptyManageState: {
    backgroundColor: COLORS.panelAlt,
    borderColor: COLORS.line,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: 12,
  },
  emptyManageText: {
    color: COLORS.muted,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },

  importPanel: {
    gap: SPACING.sm,
    backgroundColor: COLORS.panel,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.createCrayon,
    padding: 12,
  },
  importTitle: {
    color: COLORS.createDeep,
    fontSize: 15,
    fontWeight: '900',
  },
  importHelp: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  importOptionRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  importOption: {
    flex: 1,
    minHeight: 42,
    borderRadius: RADIUS.md,
    paddingHorizontal: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.panelAlt,
    borderColor: COLORS.line,
    borderWidth: 1,
  },
  importOptionActive: {
    backgroundColor: COLORS.createSoft,
    borderColor: COLORS.createCrayon,
  },
  importOptionText: {
    color: COLORS.ink,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  importOptionTextActive: {
    color: COLORS.createDeep,
  },
  importDangerOption: {
    backgroundColor: COLORS.dangerSoft,
    borderColor: COLORS.dangerCrayon,
  },
  importDangerText: {
    color: COLORS.danger,
  },
  importDeckNameInput: {
    minHeight: 46,
  },
  importTextInput: {
    minHeight: 150,
    maxHeight: 240,
  },
  importButtonColumn: {
    gap: SPACING.sm,
  },
  importActionButton: {
    position: 'relative',
    overflow: 'hidden',
    minHeight: 46,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.createSoft,
    borderColor: COLORS.createCrayon,
    borderWidth: 1,
  },
  importActionButtonText: {
    color: COLORS.createDeep,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  importBackupButton: {
    minHeight: 44,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.reviewSoft,
    borderColor: COLORS.reviewCrayon,
    borderWidth: 1,
  },
  importBackupButtonText: {
    color: COLORS.reviewDeep,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  backupPanel: {
    gap: SPACING.sm,
    borderTopColor: COLORS.line,
    borderTopWidth: 1,
    paddingTop: SPACING.sm,
    marginTop: 2,
  },
  backupTextInput: {
    minHeight: 120,
    maxHeight: 220,
    fontSize: 12,
    lineHeight: 17,
  },
  importDivider: {
    height: 1,
    backgroundColor: COLORS.line,
    marginVertical: 4,
  },
  deckSummary: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    paddingTop: 4,
  },
  metric: {
    color: COLORS.createDeep,
    fontSize: 22,
    fontWeight: '800',
  },
  metricLabel: {
    color: COLORS.muted,
    fontSize: 13,
    marginRight: 8,
  },
});
